version: "3.9"
services:
  app:
    tty: true
    stdin_open: true
    command: bin/dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
    networks:
      - inspecta
    ports:
      - 3000:3000
    environment:
      - RAILS_LOG_TO_STDOUT=1
      - DATABASE_NAME=inspecta_development 
      - DATABASE_USER=postgres 
      - DATABASE_PASSWORD=postgres 
      - DATABASE_PORT=5432 
      - DATABASE_HOST=db 
      - REDIS_URL=redis://redis:6379
      - RAILS_MAX_THREADS=1
      - WEB_CONCURRENCY=0
    depends_on:
      - db
      - redis
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - inspecta
    ports:
      - 5432:5432
  redis:
    image: redis
    networks:
      - inspecta
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
  node_modules:
networks:
  inspecta:
