default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hook_development
  username: postgres
  password: postgres
  host: localhost
  port: 5432
test:
  <<: *default
  database: hook_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432
production:
  <<: *default
  database: hook_production
  username: hook
  password: <%= ENV["HOOK_DATABASE_PASSWORD"] %>
