default: &default
  adapter: sqlite3
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/inspecta_development.sqlite3
test:
  <<: *default
  database: db/inspecta_test.sqlite3
production:
  <<: *default
  database: db/inspecta_production.sqlite3
